name: Agente Documentador IA

on:
  #schedule:
    # Se ejecuta todos los lunes a las 23:20 (Por ahora no dejaremos que se ejecute)
    #- cron: '0 0 * * 1'
  workflow_dispatch: #Tambien se puede ejecutar desde Actions

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  run-doc-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r scripts/agents/requirements.txt

      - name: Ejecutar Agente Documentador
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        run: python scripts/agents/doc_agent.py